### ISSUE TITLE
code

### ISSUE THREAD

**Issue by zw76859420** [jymsuper/VAD_tutorial#1]
thanks for your code in the github!
  I have a question about your project. How do you get the alignment from the speech?
yours

**Comment by jymsuper** [comment]
Thanks for your interest in the github!
I applied Sohn VAD to the speech corpus to generate labels.
The results of Sohn VAD are used as labels of the speech.
You can refer the below papers.
[1] Joint learning using denoising variational autoencoders for voice activity detection
[2] Boosting contextual information for deep neural network based voice activity detection

**Comment by zw76859420** [comment]
Thanks a lot.
  Can i have your contact information(E-mail and so on)?
Thanks

**Comment by jymsuper** [comment]
You can contact me through "dudans@kaist.ac.kr"

**Comment by zw76859420** [comment]
Okay, I have received your E-mail.
Thanks

**Comment by zw76859420** [comment]
I am a Speech Recognition researcher， and can i receive your data for vad experiment？


On 10/17/2019 19:26, dudans wrote:

You can contact me through "dudans@kaist.ac.kr"

**Comment by zw76859420** [comment]
I'm very sorry for interrupting you.
I don't know that how did you got the alignment labels for VAD?
Thanks for your kind reply.




On 10/17/2019 19:35, 张威 wrote:
I am a Speech Recognition researcher， and can i receive your data for vad experiment？


On 10/17/2019 19:26, dudans wrote:

You can contact me through "dudans@kaist.ac.kr"

**Comment by jymsuper** [comment]
As I said above, we applied the Sohn VAD to each utterance.
Sohn VAD is the unsupervised learning-based method, so we do not need to train the model.
The results from the Sohn VAD are binary labels (1 for speech, 0 for non-speech).
Therefore, we can use this output as the label for the DNN-based VAD.

You can use any unsupervised learning-based VAD for the label generator.
Even a simple model can yield very good results in VAD for clean speech.

**Comment by zw76859420** [comment]
Thanks a lot.





On 10/18/2019 14:21, dudans wrote:

As I said above, we applied the Sohn VAD to each utterance.
Sohn VAD is the unsupervised learning-based method, so we do not need to train the model.
The results from the Sohn VAD are binary labels (1 for speech, 0 for non-speech).
Therefore, we can use this output as the label for the DNN-based VAD.

You can use any unsupervised learning-based VAD for the label generator.
Even a simple model can yield very good results in VAD for clean speech.

**Comment by zw76859420** [comment]
Hi dudans, i felt very sorry to bother you so late.
  Now, I'm downloading your project.
  As the question above, i still don't konw how did you get the labels. And from the script you uploaded on the github, i don't find any section about how to generate the labels.
In the script which is named 'configure.py',  i don't find any information about 'LABEL_DIR' in your script. Is there any problems? And i want to konw how to generate the labels in detail.
  Also, we can improve the model accuracy by using 'N-DenseNet' which is proposed by us.
Thank you for your kind reply!
Jiangnan University, China






At 2019-10-18 14:21:04, "dudans" <notifications@github.com> wrote:


As I said above, we applied the Sohn VAD to each utterance.
Sohn VAD is the unsupervised learning-based method, so we do not need to train the model.
The results from the Sohn VAD are binary labels (1 for speech, 0 for non-speech).
Therefore, we can use this output as the label for the DNN-based VAD.

You can use any unsupervised learning-based VAD for the label generator.
Even a simple model can yield very good results in VAD for clean speech.

**Comment by jymsuper** [comment]
There is no section that is related to generating labels.
I generated labels and features using matlab codes and uploaded the results in the github.
And I didn't include the matlab code in this github.
You have to write down the codes to generate labels.
There are many codes about unsupervised learning based VAD in the github.
In the matlab voicebox toolkit, there is Sohn VAD code or you can use the other VAD in the below.
http://cs.uef.fi/pages/tkinnu/VQVAD/VQVAD.zip.

The detailed explanation is in my previous answer.

**Comment by zw76859420** [comment]
okay! 
  Thank you very much!








At 2019-10-18 21:26:50, "dudans" <notifications@github.com> wrote:


There is no section that is related to generating labels.
I generated labels and features using matlab codes and uploaded the results in the github.
And I didn't include the matlab code in this github.
You have to write down the codes to generate labels.
There are many codes about unsupervised learning based VAD in the github.
In the matlab voicebox toolkit, there is Sohn VAD code or you can use the other VAD in the below.
http://cs.uef.fi/pages/tkinnu/VQVAD/VQVAD.zip.

The detailed explanation is in the my previous answer.
